// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIbPk5uiE8euiADve_paq1QfXx2kYEdpw',
    appId: '1:584437948780:web:be2adb8f59dc4261d81349',
    messagingSenderId: '584437948780',
    projectId: 'bookstore-fbf84',
    authDomain: 'bookstore-fbf84.firebaseapp.com',
    storageBucket: 'bookstore-fbf84.firebasestorage.app',
    measurementId: 'G-SYEFGVB53V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDQ3yQtiDrAiDifSIzTAUKBoRFmj4br9I',
    appId: '1:584437948780:android:8068b65655e25bcdd81349',
    messagingSenderId: '584437948780',
    projectId: 'bookstore-fbf84',
    storageBucket: 'bookstore-fbf84.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDh1Q3dlGEgrB8iXD0eQF-GGer1v_nQmes',
    appId: '1:584437948780:ios:944ffa79c5cb525fd81349',
    messagingSenderId: '584437948780',
    projectId: 'bookstore-fbf84',
    storageBucket: 'bookstore-fbf84.firebasestorage.app',
    iosBundleId: 'com.example.bookdukan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDh1Q3dlGEgrB8iXD0eQF-GGer1v_nQmes',
    appId: '1:584437948780:ios:944ffa79c5cb525fd81349',
    messagingSenderId: '584437948780',
    projectId: 'bookstore-fbf84',
    storageBucket: 'bookstore-fbf84.firebasestorage.app',
    iosBundleId: 'com.example.bookdukan',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCIbPk5uiE8euiADve_paq1QfXx2kYEdpw',
    appId: '1:584437948780:web:446c3eab7b104b2ed81349',
    messagingSenderId: '584437948780',
    projectId: 'bookstore-fbf84',
    authDomain: 'bookstore-fbf84.firebaseapp.com',
    storageBucket: 'bookstore-fbf84.firebasestorage.app',
    measurementId: 'G-GS5S7EPGPQ',
  );
}
